FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
RUN apt-get update
RUN pip3 install flask
RUN pip3 install pillow
# RUN mkdir -p /hone/vscode/codeserver
# COPY vscode_cli_alpine_arm64_cli.tar.gz /home/vscode/codeserver/vscode_cli_alpine_arm64_cli.tar.gz
# WORKDIR /home/vscode/codeserver/
# RUN tar -xf vscode_cli_alpine_arm64_cli.tar.gz
# ENV PATH="${PATH}:/home/vscode/codeserver"
